baseURL = 'https://emadadel4.github.io/'
languageCode = 'ar'
title = 'Emad Adel'
paginate = 3

[Params]
 dateFormat = "Jan 2, 2006"

[taxonomies]
 author = "authors"


defaultContentLanguage = 'ar'
defaultContentLanguageInSubdir = true

[languages.en]
  contentDir = 'content/en'
  disabled = false
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  weight = 2

[languages]
  [languages.ar]
    contentDir = 'content/ar'
    languageCode = 'ar'
    languageDirection = 'rtl'
    languageName = 'عربي'
    weight = 1
