baseURL = 'https://emadadel4.github.io/'
languageCode = 'en'
title = 'Emad Adel'
paginate = 3

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
  contentDir = 'content/en'
  authorsDir = "content/en"
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  weight = 2

[languages.ar]
  contentDir = 'content/ar'
  authorsDir = "content/ar"

  languageCode = 'ar'
  languageDirection = 'rtl'
  languageName = 'عربي'
  weight = 1

[Params]
 dateFormat = "Jan 2, 2006"

[taxonomies]
 author = "authors"
